server:
  port: 8000

spring:
  application:
    name: gateway-service
  # Spring Cloud Gateway? ?? API ??? ????? ??? ??.
  cloud:
    gateway:
      mvc:
        routes:
          # ? ???? ???
          - id: first-service
            # ?? 8081?? ?? ?? ???? ??? ??
            uri: http://localhost:8081/
            # ?????? /first-service/** ? ???? http://localhost:8081/? ???
            predicates:
              - Path=/first-service/**
          - id: second-service
            uri: http://localhost:8082/
            predicates:
              - Path=/second-service/**
