server:
  port: 8080

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#  datasource:
#    url: jdbc:h2:mem:testdb  # 인메모리 DB를 자동 생성
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # 테이블 자동 생성
    defer-datasource-initialization: true  # ⭐ 데이터베이스 초기화 지연

# Eureka client 설정
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

greeting:
  message: Welcome to the Simple E-Commerce

#token:
#  expiration_time: 86400000
#  secret: user_token

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, bus-refresh

logging:
  level:
    com.example.userservice.client: debug