server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#  datasource:
#    url: jdbc:h2:mem:testdb  # 인메모리 DB를 자동 생성
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # 테이블 자동 생성
    defer-datasource-initialization: true  # ⭐ 데이터베이스 초기화 지연

# Eureka client 설정
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-app:8761/eureka

greeting:
  message: Welcome to the Simple E-Commerce

#token:
#  expiration_time: 86400000
#  secret: user_token

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411
  tracing:
    sampling:
      probability: 1.0  # 전체 요청 추적
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, bus-refresh, info, metrics, loggers, trace

logging:
  level:
    com.example.userservice.client: debug

resilience4j:
  circuitbreaker:
    instances:
      orderService:
        # /actuator/health에서 Circuit Breaker 상태 확인 가능하게 함
        registerHealthIndicator: true
        # 최근 10번의 호출 결과를 기준으로 실패율을 측정
        slidingWindowSize: 10
        # 실패율이 50% 이상이면 Circuit Breaker가 열림 (OPEN) 상태로 전환
        failureRateThreshold: 50
        # OPEN 상태에서 10초 동안 기다린 후, Half-Open 상태로 전환 시도
        waitDurationInOpenState: 10s
        # Half-Open 상태에서 최대 3번 호출을 시도하고, 모두 성공하면 Circuit 닫힘(Closed)
        permittedNumberOfCallsInHalfOpenState: 3