server:
  port: 8081

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop  # ??? ?? ??
    defer-datasource-initialization: true  # ? ?????? ??? ??
    show-sql: true
    generate-ddl: true

# Eureka client ??
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

greeting:
  message: Welcome to the Simple E-Commerce

logging:
  level:
    com.example.orderservice: debug