services:
  user-db:
    image: mysql:8
    container_name: user-db
    environment:
      MYSQL_DATABASE: userdb
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}        # ✅ 자동 사용자 생성
      MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}    # ✅ 해당 계정 비밀번호
    ports:
      - "3308:3306"
    volumes:
      - user-db-data:/var/lib/mysql

  user-app:
    build:
      context: .
      dockerfile: dockerFile
    container_name: user-app
    ports:
      - "8081:8080"
    depends_on:
      - user-db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://user-db:3306/userdb
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092

volumes:
  user-db-data:
